FROM sonarqube:alpine
LABEL contributor.1="@nicxvan nlightened Development LLC <nic@nlighteneddevelopment.com>" \
      contributor.2="@aloyr HID Global" \
      contributor.4="@bariman HID Global" \
      contributor.4="@thepolyglot HID Global" \
      contributor.5="@chrisoconnor001 Hearts of Oak, LLC"